# Hand-run scouting analysis (analysis/scouting.yaml v0.2-draft) by claude-opus-5-5,
# read from bakeoff/jobs_sample.jsonl. One row per job id:
#   overlap, stretch, stretch_reasons, wildcard, ai_relevance, client_ownership,
#   workplace (what the text actually says: remote | hybrid | onsite | field_travel | unclear),
#   overlap_points, caveats, worth_opening_because, confidence
# why_surfaced, missing_info, and derived tags are filled in by build_scouting.py.
R = {}
def r(jid, overlap, stretch, reasons, wildcard, ai, client, workplace, points, caveats, worth, conf="high"):
    R[jid] = dict(overlap=overlap, stretch=stretch, stretch_reasons=reasons, wildcard=wildcard, ai_relevance=ai,
                  client_ownership=client, workplace=workplace, overlap_points=points, caveats=caveats,
                  worth_opening_because=worth, confidence=conf)

# --- chunk 1 ---
r(851334603, "very_low", "none", [], False, "adjacent", "none", "unclear", ["helps draft/standardize SOPs and training"], ["summer internship", "part-time", "Chicago listed"], "Not for you unless you want an internship.")
r(852240587, "very_low", "big", ["7-10+ yrs enterprise tech sales"], False, "present", "owns_accounts", "field_travel", [], ["quota-carrying field sales", "Northeast territory travel"], "Matched 'AI adoption' as a sales pitch, not learning work.")
r(851325384, "very_low", "none", [], False, "present", "none", "onsite", [], ["posting says 'Onsite - Sawtelle', mislabeled remote"], "Mislabeled onsite ops role; skip.")
r(852259999, "weak", "big", ["VP", "10+ yrs leadership", "runs large services org"], False, "adjacent", "supporting", "remote", ["K-12 adoption playbooks and frameworks"], ["executive services leadership, not content"], "Ed-tech adoption strategy at VP level; content is a small slice.", "medium")
r(851879370, "very_low", "big", ["8+ yrs professional services", "ServiceNow specialty"], False, "present", "supporting", "field_travel", ["trains customers to write user stories"], ["travel up to 50%", "contract"], "ServiceNow consulting; skip.")
r(851978538, "very_low", "some", ["3+ yrs digital PM"], False, "present", "supporting", "unclear", ["coordinates creative/digital production"], ["agency PM", "NYC listed"], "Agency project management; minimal content ownership.")
r(852300247, "very_low", "some", ["3+ yrs managing technical staff", "full-stack knowledge"], False, "present", "none", "remote", ["employer makes health curricula"], ["IT/tech management role"], "Curriculum nonprofit, but the job is IT.")
r(852179389, "very_low", "big", ["6+ yrs software dev", "people manager"], False, "present", "none", "remote", [], ["engineering management"], "Engineering manager; skip.")
r(852185468, "very_low", "big", ["15+ yrs client-facing"], False, "present", "owns_accounts", "unclear", [], ["federal customer success exec"], "Enterprise CS exec; skip.")
r(851954060, "very_low", "big", ["sales leadership"], False, "present", "owns_accounts", "remote", [], ["quota/ARR sales leadership", "duplicate of 851910891/852012600"], "Sales director; skip.")
r(852195306, "partial", "some", ["Salesforce Marketing Cloud production"], True, "present", "none", "remote", ["writes and edits all fundraising email copy in multiple brand voices", "uses AI tools to streamline copy-editing"], ["3-month contract to 1/4/2027", "20 hrs/week at $42/hr", "fundraising, not learning"], "Short, remote writing gig at Khan Academy; a stopgap or portfolio piece, found on Greenhouse.")
r(852260754, "partial", "big", ["8+ yrs change management", "dotted-line lead of functional leads"], True, "central", "none", "hybrid", ["develops and delivers AI training programmes", "maintains learning materials and enablement guides for AI tools", "runs AI champions network"], ["Reston VA part-time telework = hybrid, fails 100% remote", "construction-industry AI programme"], "Genuinely AI-enablement content work, but hybrid in Reston.", "high")
r(851910891, "very_low", "big", ["sales leadership"], False, "present", "owns_accounts", "unclear", [], ["duplicate Smartcat sales director"], "Duplicate; skip.")
r(852132932, "weak", "some", ["3+ yrs SaaS support"], False, "none", "supporting", "remote", ["supports learners/admins on an e-learning platform"], ["phone/chat support queue"], "L&D-industry support role; adjacent only.")
r(852185191, "partial", "some", ["travel up to 35%"], False, "present", "none", "remote", ["hands-on content design and delivery", "owns LMS and learning calendar", "uses AI to improve learning reach"], ["travel up to 35% to communities", "$65-70k", "heavy compliance/logistics share"], "Real L&D content work, remote, modest pay and real travel.")
r(852012600, "very_low", "big", ["sales leadership"], False, "present", "owns_accounts", "unclear", [], ["duplicate Smartcat sales director (company spelled 'smARTcat')"], "Duplicate; skip.")
r(851383703, "strong", "some", ["maintains training lab servers/databases"], False, "none", "none", "remote", ["designs ILT, vILT and eLearning content", "owns needs analysis, curriculum design, content development", "writes lab guides and technical docs"], ["technical product (contact-center analytics)", "listed Atlanta; 'telecommuting permitted'"], "Core content-development job for a software product.")
r(851194095, "strong", "big", ["5+ yrs instructional design", "3+ yrs government BD/capture experience"], False, "present", "none", "remote", ["instructional design and curriculum development", "course modernization", "AI-enabled content development tools"], ["part-time", "$60-75k", "government-contracting BD domain required"], "Content development plus AI tooling; domain ask is the stretch.")
r(852109042, "very_low", "big", ["Master's/PhD in physics"], False, "none", "supporting", "field_travel", ["physics training curriculum"], ["medical physicist credential"], "Credentialed physics role; skip.")
r(852303520, "partial", "big", ["8+ yrs engineering/technical troubleshooting", "X-ray/imaging domain"], True, "none", "none", "unclear", ["creates curricula, course materials, online modules, video tutorials", "instructor guides"], ["may require living near Lafayette CO", "25% travel", "deep equipment domain"], "Technical curriculum work at Medtronic; check the location line.", "medium")
r(851886792, "very_low", "big", ["7-10 yrs infosec"], False, "none", "none", "remote", [], ["security leadership"], "Skip.")
r(851780050, "very_low", "big", ["MD/DO required"], False, "none", "none", "onsite", ["develops residency curriculum"], ["physician role"], "Skip.")
r(851924911, "very_low", "big", ["RN/NP license"], False, "none", "none", "field_travel", ["patient education"], ["nurse licensure", "weekly overnight travel"], "Skip.")
r(852286299, "strong", "big", ["Director", "5+ yrs onboarding/education", "3+ yrs owning a program", "hiring"], True, "none", "supporting", "remote", ["builds customer enablement library: knowledge base, tutorial videos, one-pagers, training decks", "builds internal enablement curriculum", "content governance model"], ["travel up to 20%", "also runs onboarding operations", "legal-services niche"], "Build-the-content-system-from-scratch role, off the major boards (Workable).")
r(851780203, "very_low", "none", [], False, "none", "owns_accounts", "onsite", [], ["summer internship, NYC", "Mandarin required"], "Skip.")
r(851886791, "very_low", "big", ["7-10 yrs infosec"], False, "none", "none", "remote", [], ["duplicate MLabs posting"], "Duplicate; skip.")
r(851626794, "very_low", "big", ["PhD required"], False, "present", "none", "onsite", ["curriculum redesign"], ["academic dept chair in Lynchburg VA", "company field wrong ('Women In Science')"], "Skip.")
r(851814387, "very_low", "some", [], False, "none", "owns_accounts", "field_travel", [], ["territory sales"], "Skip.")
r(851730899, "very_low", "big", ["clinical perfusion"], False, "none", "owns_accounts", "field_travel", ["customer training as part of sales"], ["75% travel"], "Skip.")
r(851854234, "weak", "big", ["8+ yrs B2B SaaS product marketing"], False, "present", "supporting", "unclear", ["seller enablement and messaging"], ["product-marketing leadership"], "PMM with enablement slice; long shot.", "medium")
r(852095008, "very_low", "big", ["engineering/life-science tech"], False, "none", "supporting", "field_travel", [], [], "Skip.")
r(852332773, "weak", "some", ["2+ yrs CSM"], False, "none", "owns_accounts", "remote", ["onboarding guidance"], ["portfolio of accounts", "travel-industry software"], "Customer success; skip unless pivoting.")
r(852303517, "very_low", "big", ["4-8+ yrs med-device sales"], False, "present", "owns_accounts", "field_travel", [], ["territory sales"], "Skip.")
r(851833212, "weak", "some", ["3+ yrs implementation PM"], False, "none", "supporting", "remote", ["customer training during implementations"], ["project/implementation role"], "Implementation PM; weak match.")
r(851324275, "very_low", "big", ["5+ yrs flow cytometry"], False, "none", "owns_accounts", "field_travel", [], ["85% travel"], "Skip.")
r(852191722, "very_low", "some", [], False, "none", "owns_accounts", "field_travel", [], ["territory sales, 50% travel"], "Skip.")

# --- chunk 2 ---
r(851750720, "very_low", "big", ["8+ yrs cloud product mgmt"], False, "present", "supporting", "remote", [], ["contract, 'independent visa only'"], "Product management; skip.")
r(852160489, "very_low", "none", [], False, "none", "owns_accounts", "remote", [], ["commission-based referral sales"], "Commission sales; skip.")
r(851612227, "very_low", "big", ["7+ yrs partnerships"], False, "present", "owns_accounts", "remote", ["partner certification playbooks"], ["alliances/revenue role"], "Skip.")
r(852160465, "very_low", "big", ["7+ yrs solutions engineering"], False, "none", "owns_accounts", "remote", ["customer workshops"], ["DACH region pre-sales"], "Skip.")
r(852099340, "very_low", "some", ["3-8 yrs CSM"], False, "none", "owns_accounts", "unclear", ["onboarding"], ["renewal/expansion ownership"], "Skip.")
r(852283066, "very_low", "big", ["7+ yrs AppSec"], False, "present", "none", "remote", ["writes secure-development guidance"], ["security engineering"], "Skip.")
r(851635315, "very_low", "big", ["3+ yrs SE", "quote-to-cash domain"], False, "present", "supporting", "unclear", ["technical enablement assets"], ["pre-sales engineering", "aggregator listing (Jobgether)"], "Skip.")
r(851795970, "weak", "none", ["1-3 yrs"], False, "present", "supporting", "remote", ["owns partner enablement content and marketing toolkits", "asset libraries"], ["early-career demand-gen marketing", "aggregator listing (TalentHop), client unnamed"], "Enablement-content slice in a junior marketing role.", "medium")
r(851894877, "very_low", "big", ["5-8 yrs SE"], False, "none", "owns_accounts", "field_travel", [], ["onsite customer travel"], "Skip.")
r(851914769, "very_low", "some", ["5 yrs service desk"], False, "none", "none", "remote", ["trains service desk staff"], ["IT help desk"], "Skip.")
r(852211120, "very_low", "big", ["10 yrs sales/marketing", "surgical domain"], False, "none", "supporting", "field_travel", [], ["global travel"], "Skip.")
r(852327643, "very_low", "none", [], False, "none", "none", "unclear", ["documentation"], ["app support; Austin listed"], "Skip.")
r(852052007, "very_low", "none", [], False, "present", "none", "unclear", [], ["tech support"], "Skip.")
r(851876382, "weak", "some", [], False, "none", "owns_accounts", "remote", ["frameworks and best-practice standards for clients"], ["client advisory on key accounts"], "Skip unless client-facing is OK.")
r(852139317, "very_low", "some", [], False, "none", "none", "unclear", [], ["systems analyst, Moore OK"], "Skip.")
r(851409157, "weak", "none", [], False, "none", "supporting", "unclear", ["user onboarding and training"], ["support queue"], "Skip.")
r(851325805, "very_low", "none", [], False, "none", "none", "remote", [], ["$17/hr call center", "veteran-affiliated sourcing"], "Skip.")
r(852159736, "very_low", "none", [], False, "none", "none", "remote", [], ["$17/hr customer service", "4 identical postings (ids differ)"], "Skip.")
r(851795978, "very_low", "big", ["ML engineering"], False, "central", "none", "remote", [], ["ML engineer; matched 'AI' title words"], "Skip.")
r(851544831, "partial", "some", ["4+ yrs program management", "people lead of one PM"], False, "central", "none", "unclear", ["coordinates content, video and architecture pods shipping AI courses", "runs release readiness for learning programs", "sits inside Udacity's learning-experience org"], ["program management rather than hands-on content", "NY listed; MD pay band listed so MD looks eligible"], "Udacity (Accenture) AI-course production ops; adjacent-to-core with strong AI angle.")
r(852184495, "very_low", "some", ["SAP finance"], False, "present", "none", "unclear", [], ["finance data analyst, Irvine"], "Skip.")
r(851122931, "very_low", "big", ["VP data architecture"], False, "central", "none", "remote", [], ["data/ML leadership"], "Skip.")
r(850776361, "very_low", "big", ["ML engineering", "TS/SCI with poly"], False, "central", "none", "onsite", [], ["Laurel MD, clearance required"], "Skip.")
r(851281618, "very_low", "big", ["5+ yrs SWE", "MCP/platform infra"], False, "central", "none", "unclear", [], ["platform engineering"], "Skip.")
r(851442949, "very_low", "big", ["8-15 yrs ops leadership"], False, "central", "none", "unclear", ["AI adoption internally"], ["Houston preferred", "builds AI tools, ops VP"], "Skip.")
r(852099703, "partial", "none", [], False, "none", "owns_accounts", "remote", ["writes social copy and monthly content calendars", "designs graphics and short videos"], ["$2,000/month part-time", "direct client management", "social media, not learning"], "Small remote content gig; low pay.")
r(851275561, "partial", "some", ["5+ yrs UX writing/content design"], False, "none", "none", "unclear", ["content design for digital health experiences", "runs workshops/crits"], ["UX content design, not learning content", "Boston listed; remote unclear"], "Content-design title family working as intended; UX flavor.", "medium")
r(851500590, "weak", "big", ["5+ yrs PR/media relations"], False, "none", "none", "unclear", ["editorial content, social strategy"], ["press/media relations core", "Houston; some travel"], "Comms role; weak.")
r(850232990, "weak", "some", ["illustration portfolio"], False, "none", "none", "unclear", ["turns pet-care information into illustrated educational content"], ["illustrator role", "1-person startup, contract"], "Illustration-first; skip unless you draw.")
r(851058374, "partial", "some", ["exceptional long-form technical writing"], False, "central", "none", "unclear", ["explainer content on AI safety, evaluation, governance", "case studies and reference materials", "content process"], ["marketing/thought-leadership content", "LA listed; remote unclear"], "AI-central content lead at a small AI-safety company.")
r(850746530, "partial", "some", ["SEO depth"], False, "none", "none", "remote", ["help center and FAQ content structure, voice and governance"], ["4-month contract via staffing firm"], "Help-center content governance; short contract.")
r(851302965, "weak", "big", ["trade-journalist knowledge of CX outsourcing"], False, "none", "supporting", "remote", ["executive ghostwriting, research-based pieces"], ["contractor", "niche beat required"], "Editorial ghostwriting; niche.")
r(850947082, "strong", "none", [], False, "none", "none", "remote", ["develops, maintains and delivers curricula and course content", "needs assessment"], ["must live within 60 miles of an HCA hospital in FL/GA/ID/KS/KY/MO/NV/NH/NC/SC/TN/TX/UT/VA; Maryland not listed", "duplicate of 850274105 under company 'Work From Home'"], "Exactly the work, but Maryland is excluded.")
r(850792055, "strong", "big", ["demonstrable AI-agent building", "API tooling (Git/Postman)", "3+ yrs technical training"], False, "central", "none", "remote", ["builds training for customers/partners on agentic AI", "technical curriculum development", "builds demo agents"], ["says 'do not apply if you have dabbled with AI agents'"], "AI-central curriculum role at Veeva; stretch is hands-on agent building.")
r(850357921, "strong", "big", ["2+ yrs music classroom teaching"], False, "none", "none", "remote", ["designs video scripts, assessments, written lessons", "writes measurable objectives"], ["$25-34.50/hr", "music teaching background required"], "Pure curriculum development, but needs music-teacher background.")
r(850274105, "strong", "none", [], False, "none", "none", "remote", ["develops, maintains and delivers curricula and course content"], ["must live near an HCA hospital; Maryland not in the state list"], "Exactly the work, but Maryland is excluded.")

# --- chunk 3 ---
r(851123114, "strong", "some", ["oil & gas / safety domain"], False, "none", "none", "remote", ["designs curricula, learning paths, participant guides, assessments, job aids", "ILT, virtual and e-learning", "job task analysis"], ["contract Oct 2026-Mar 2027 via staffing firm", "technical/safety/compliance content"], "Textbook training-development contract; remote; apply link on Loxo, not the boards.")
r(850645504, "strong", "big", ["7+ yrs curriculum/instructional leadership", "manages team"], False, "none", "none", "remote", ["leads curriculum materials and instructional programs", "instructional standards and accessibility"], ["client unnamed (Ladders listing)", "licensure-aligned content"], "Senior curriculum leadership, remote, $102-132k.")
r(849812736, "strong", "some", ["K-12 math/science/CS subject depth"], False, "present", "none", "remote", ["writes questions, hints, step-by-step explanations", "maps to standards", "reviews AI-assisted drafts"], ["contract", "subject-matter depth required"], "Curriculum writing with AI-draft review; contract.")
r(852088703, "very_low", "none", [], False, "none", "none", "unclear", [], ["Maine-based school attendance coordinator", "matched on 'academy'"], "Skip; 'academy' title term is noisy.")
r(852327467, "partial", "big", ["5+ yrs customer education in MedTech/imaging", "team manager"], False, "adjacent", "supporting", "field_travel", ["builds scalable training programs and education assets", "learning pathways"], ["travel 30-40% incl. international", "radiology domain"], "Customer-education manager; travel and domain heavy.")
r(852034349, "strong", "some", ["3-5 yrs content + PM"], False, "none", "supporting", "unclear", ["owns customer-success content ecosystem", "sales enablement training", "customer stories library"], ["Centennial CO listed; must travel to Arrow office on request"], "Content + enablement ownership; check remote status.", "medium")
r(852260927, "partial", "big", ["Director", "strategy ownership"], False, "none", "none", "remote", ["customer education programs across modalities", "training KPIs"], ["listed salary $50k looks wrong for a director", "some travel"], "Director of customer education at a digital-signage firm; salary field suspicious.", "medium")
r(851631756, "partial", "big", ["8-12 yrs customer education/PS"], False, "present", "supporting", "remote", ["custom education programs for enterprise accounts"], ["consultative, account-embedded", "aggregator listing (TalentHop), client unnamed", "duplicate of 852156681"], "Enterprise customer-education consulting.")
r(852201874, "strong", "some", ["LMS selection/config"], False, "none", "none", "remote", ["builds first customer training program from scratch", "learner personas", "foundational curriculum and how-to content"], ["contract", "DC office preferred, remote open"], "Build-it-from-zero customer education; good portfolio role.")
r(852156681, "partial", "big", ["8-12 yrs"], False, "present", "supporting", "remote", ["custom education programs"], ["duplicate of 851631756"], "Duplicate; skip.")
r(851873213, "strong", "some", ["3-5 yrs ID in contact center"], False, "none", "none", "unclear", ["new-hire and continuing-ed curricula", "e-learning modules, simulations, job aids"], ["NYC public hospital system; likely onsite/hybrid"], "Solid ID role; likely not remote.", "medium")
r(851964581, "partial", "big", ["licensed clinician with 3+ yrs post-grad clinical"], False, "none", "supporting", "field_travel", ["ADDIE curriculum, clinical training materials"], ["clinical license required", "travel up to 30%"], "Blocked by clinical credential.")
r(851969875, "strong", "none", [], False, "none", "none", "unclear", ["designs live and digital learning", "onboarding redesign", "leadership learning experience"], ["contract via staffing firm", "Sacramento listed; facilitation"], "LXD contract; check location.", "medium")
r(851079619, "strong", "none", [], False, "present", "none", "unclear", ["develops online courses in LMS", "uses AI tools for course design and drafting"], ["religious university (biblical worldview requirement)", "Greenville SC listed"], "Online course ID with AI tooling; faith-based employer.")
r(850576240, "strong", "none", [], False, "none", "none", "remote", ["partners with faculty to design online courses", "UDL/accessibility", "Canvas"], ["higher-ed pay likely"], "Clean remote higher-ed instructional designer role.")
r(850873020, "strong", "some", ["healthcare education topics", "faculty consultation"], False, "none", "none", "unclear", ["instructional materials, videos, simulations, modules"], ["Oshkosh WI; remote unclear"], "Strong ID match; confirm remote.", "medium")
r(851969865, "strong", "none", [], False, "none", "none", "unclear", ["digital training materials, video, e-learning, podcasts", "storyboarding and scripting"], ["contract via staffing firm", "Libertyville IL listed"], "ID contract; confirm remote.", "medium")
r(851917710, "partial", "big", ["active TS/SCI with polygraph", "BA + 8 yrs", "DoD 8570"], False, "none", "none", "onsite", ["technical documentation, templates, style"], ["onsite DC/Elkridge MD", "clearance required; mislabeled remote"], "Mislabeled onsite cleared role.")
r(849282368, "weak", "none", [], True, "central", "none", "remote", ["editorial judgment on AI-generated writing"], ["AI-evaluation gig via micro1", "contract $90-140/hr"], "AI writing-evaluation gig; decent hourly side work.")
r(849158527, "weak", "none", [], True, "central", "none", "remote", ["evaluates instructional/technical content readability"], ["AI-evaluation gig", "$100/hr"], "AI-evaluation side gig.")
r(850033302, "partial", "some", ["technical AI audience"], False, "central", "none", "remote", ["public-facing technical writing about AI data work"], ["10-15 hrs/week, $60/hr, 6-month contract"], "Part-time AI content writing (Ashby, off-board).")
r(849943073, "very_low", "big", ["3+ yrs hands-on AI research"], False, "central", "supporting", "unclear", [], ["developer relations for AI researchers"], "Skip.")
r(850608574, "strong", "none", [], False, "none", "none", "remote", ["writes instructional content, practice questions, answer explanations"], ["$20-35/hr project-based"], "Real instructional writing; low pay.")
r(849294484, "strong", "some", ["3-5 yrs tech + developer audience"], False, "present", "none", "unclear", ["creates product training and technical learning content", "scripts/narrates video", "uses AI tools for content creation"], ["Texas listed; remote unclear"], "Core technical training content role at BigCommerce parent.")
r(851708195, "very_low", "big", ["I/O psychologist/psychometrics"], False, "present", "none", "unclear", [], ["people analytics"], "Skip.")
r(851954268, "very_low", "big", ["8+ yrs cloud networking"], False, "none", "owns_accounts", "unclear", [], [], "Skip.")
r(852220658, "very_low", "none", [], False, "present", "none", "remote", ["updates knowledge base"], ["tech support; aggregator listing"], "Skip.")
r(851823432, "very_low", "none", [], False, "none", "none", "remote", [], ["$17/hr CSR, duplicate family of Moen postings"], "Skip.")
r(852303345, "very_low", "big", ["10 yrs"], False, "none", "supporting", "field_travel", [], ["duplicate of 852211120 (different company string)"], "Duplicate; skip.")
r(851721498, "very_low", "none", [], False, "none", "none", "remote", [], ["CSR; same Moen family via TalentHop"], "Skip.")
r(852195349, "very_low", "big", ["10+ yrs AI/solution architecture", "Dynamics 365"], False, "central", "owns_accounts", "remote", ["AI adoption across firm"], ["technical leadership"], "Skip.")
r(851562109, "very_low", "big", ["IT management"], False, "none", "none", "onsite", [], ["Richmond VA state IT"], "Skip.")
r(852159738, "very_low", "none", [], False, "none", "none", "remote", [], ["Moen CSR duplicate"], "Skip.")
r(852214455, "very_low", "some", ["5+ yrs support", "Public Trust"], False, "none", "none", "remote", ["writes KB troubleshooting docs"], ["Tier 3 help desk"], "Skip.")
r(852159733, "very_low", "none", [], False, "none", "none", "remote", [], ["Moen CSR duplicate"], "Skip.")
r(851997846, "very_low", "big", ["TS/SCI poly"], False, "none", "none", "onsite", [], ["data center, Chantilly VA"], "Skip.")

# --- chunk 4 ---
r(852159737, "very_low", "none", [], False, "none", "none", "remote", [], ["Moen CSR duplicate"], "Skip.")
r(851469145, "very_low", "none", [], False, "present", "none", "unclear", [], ["tech support"], "Skip.")
r(852068689, "very_low", "big", ["5+ yrs government bids"], False, "none", "none", "unclear", ["maintains bidding knowledge base"], ["bid management"], "Skip.")
r(852245403, "very_low", "some", ["3+ yrs support"], False, "none", "none", "remote", ["creates simple support training"], ["support team lead"], "Skip.")
r(851933440, "very_low", "none", [], False, "none", "none", "onsite", [], ["SOC internship"], "Skip.")
r(851742356, "weak", "big", ["4-7+ yrs demand gen"], False, "none", "none", "remote", ["campaign content"], ["growth marketing", "aggregator listing (Jobgether)"], "Skip.")
r(852177718, "weak", "big", ["8-10 yrs PMM"], False, "none", "none", "remote", ["sales enablement materials, customer-facing content"], ["12-month contract", "product marketing"], "PMM contract with enablement content; long shot.", "medium")
r(851812300, "very_low", "none", [], False, "none", "supporting", "remote", ["KB content upkeep"], ["support; aggregator repost of PLACE role"], "Skip.")
r(852083080, "partial", "big", ["senior leadership across a global NGO", "chairs exec forums", "dotted-line management"], True, "central", "none", "remote", ["oversees development and rollout of AI training and culture-change initiatives", "builds staff capacity to use data and AI"], ["international travel up to 20%", "strategy/leadership heavier than content", "closes 7 Oct 2026"], "AI-literacy capacity building at Save the Children; found on their own careers site.")
r(851306577, "very_low", "none", [], False, "none", "supporting", "remote", ["coaches customers on product use"], ["tier-1 support, PST hours"], "Skip.")
r(852282913, "weak", "big", ["4-7+ yrs platform/DevOps/MLOps"], True, "central", "none", "remote", ["writes AI governance artifacts and training/enablement support"], ["hands-on engineering and incident response", "defense tech"], "AI governance with enablement slice; mostly engineering.", "medium")
r(852135550, "very_low", "big", ["8+ yrs data science leadership"], False, "present", "none", "remote", [], [], "Skip.")
r(852040182, "very_low", "none", [], False, "none", "owns_accounts", "remote", [], ["bookkeeping"], "Skip.")
r(852088130, "very_low", "none", [], False, "none", "none", "unclear", [], ["HR help desk; onsite Jan-Feb for NY/NJ"], "Skip.")
r(851470310, "very_low", "big", ["test pilot", "Secret clearance"], False, "none", "none", "onsite", ["aircrew training"], ["onsite Patuxent River MD"], "Skip.")
r(851931824, "weak", "some", ["2-3 yrs implementation"], False, "none", "supporting", "unclear", ["user training during onboarding"], ["implementation PM"], "Skip.")
r(852266246, "very_low", "big", ["pharma hospital sales"], False, "none", "owns_accounts", "field_travel", [], ["80% travel"], "Skip.")
r(851634033, "very_low", "none", [], False, "none", "owns_accounts", "remote", ["client education"], ["support portfolio of 20-40 clients"], "Skip.")
r(852262101, "very_low", "big", ["5+ yrs HVAC sales"], False, "none", "owns_accounts", "field_travel", [], ["50% travel"], "Skip.")
r(852167998, "very_low", "none", [], False, "none", "supporting", "unclear", ["patient education"], ["insurance intake"], "Skip.")
r(852046205, "strong", "some", ["5+ yrs", "regulated health-insurance content"], True, "present", "none", "unclear", ["leads enterprise content governance model and taxonomy", "leads content development for regulated segments", "AI engine optimization of content"], ["title says 'Digital Product Analyst'", "NC listed; remote unclear"], "Content-governance work hiding under an analyst title; a real wildcard.")
r(851410869, "very_low", "none", [], False, "none", "supporting", "remote", [], ["early-morning email support", "clinical background preferred"], "Skip.")
r(851335042, "very_low", "big", ["6-10 yrs cardiac mapping"], False, "none", "owns_accounts", "field_travel", ["trains physicians"], [], "Skip.")
r(852335840, "very_low", "big", ["forward-deployed engineering"], False, "central", "owns_accounts", "onsite", [], ["embedded onsite with customer"], "Skip.")
r(852321441, "weak", "some", [], False, "present", "owns_accounts", "field_travel", ["learning-industry customer success"], ["client-site travel", "account ownership"], "Learning-provider CSM; client-facing.")
r(852248222, "partial", "big", ["doctoral/professional degree"], False, "none", "none", "remote", ["co-develops and co-leads a course on interprofessional education", "100% virtual teaching"], ["part-time faculty", "PhD/PharmD/MD required"], "Blocked by degree requirement.")
r(852238579, "very_low", "big", ["5+ yrs B2B sales leadership"], False, "none", "owns_accounts", "remote", ["expansion playbooks"], ["revenue team leadership"], "Skip.")
r(852216986, "weak", "big", ["8+ yrs channel sales/partner enablement"], False, "none", "owns_accounts", "field_travel", ["builds partner training, playbooks, battlecards"], ["quota-carrying", "travel up to 40%"], "Enablement inside a sales job; skip.")
r(852288354, "very_low", "some", [], False, "none", "none", "remote", [], ["IT support"], "Skip.")
r(851985369, "strong", "big", ["8-10 yrs learning design/content development"], False, "present", "none", "unclear", ["owns end-to-end instructional content creation", "builds new courses end to end incl. AI/tech courses", "works with SMEs/instructors"], ["California listed; remote not stated in excerpt"], "Near-perfect title and duties at Springboard; the years ask is the stretch.")
r(851470103, "partial", "some", ["2+ yrs hands-on scaling AI tools in SDLC"], False, "central", "supporting", "remote", ["develops playbooks, training materials, success metrics for AI tool adoption", "runs workshops upskilling teams"], ["consulting firm; client assignments", "engineering audience (Copilot, Jira AI)"], "AI-adoption enablement content, 100% remote.")
r(852286164, "strong", "big", ["deep offensive-security tradecraft (Red Team, Cobalt Strike)"], False, "none", "none", "remote", ["designs courses, modules, hands-on labs, assessments, certifications, learning paths"], ["security domain expertise required"], "Pure course development; domain is the big stretch. $115-140k.")
r(852327990, "very_low", "none", [], False, "none", "none", "onsite", ["tutoring"], ["in-school tutoring, California"], "Skip; 'academy' noise.")
r(852327987, "strong", "some", ["5+ yrs higher-ed online design"], False, "none", "none", "unclear", ["designs scalable learning experiences", "learner analysis, adult learning science"], ["Tempe AZ listed; remote unclear", "$65-70k"], "Solid LXD role; confirm remote.", "medium")
r(851952124, "partial", "some", ["3+ yrs writing role, AI-safety literacy"], False, "central", "none", "onsite", ["translates AI research into op-eds, blogs, briefs"], ["'Berkeley Office' listed; likely in-person"], "AI-central writing role; probably not remote.", "medium")
r(851865044, "very_low", "none", [], False, "none", "none", "onsite", [], ["substitute teacher, Midland TX", "from the any-workplace count query, not remote-filtered"], "Skip.")
